- hosts: test

  vars:
    - deploy_user: "{{ ansible_user_id }}"
    - tkp_version: "master"
    - tkp_shortname: "tkp-{{ tkp_version }}"
    - tkp_repo_path: "{{ repo_dir }}/{{ tkp_shortname }}"
    - tkp_venv_path: "{{ default_install_prefix }}/venvs/{{ tkp_shortname }}"

      # General case:
#    - trap_user: "trapdemo"
#    - trap_jobs_dir: "/home/{{ trap_user }}/trap-jobs"
#    - trap_data_dir: "/home/{{ trap_user }}/trap-data"
#    - trap_dbname: "{{ trap_user }}"

    # Assuming vagrant / virtualbox usage:
    - trap_user: "{{ ansible_user_id }}"
    - trap_jobs_dir: "/vagrant/trap-jobs"
    - trap_data_dir: "/vagrant/trap-data"
    - trap_dbname: "trapdemodb"
    - trap_dbpass: "trappass"

  vars_files:
    - postgres-test-vars.yml

  roles:
    - timstaley.base
    - { role: ANXS.postgresql,
        become: true
        }
    - { role: timstaley.banana,
        banana_deploy_user: "{{ deploy_user }}",
        banana_version: "master",
        banana_url_subdir: "",
        }
    - timstaley.casalibs-ppa

  tasks:
    - include: install-trap.yml
      tags: trap

    - include: run-example-job.yml
      become: yes
      become_user: "{{ trap_user }}"
      tags: example

    - name: Grant read-only privs for Banana on TraP DB
      postgresql_privs:
        db: "{{ trap_dbname }}"
        privs: SELECT
        objs: ALL_IN_SCHEMA
        type: table
        schema: public
        roles: "{{ banana_postgres_username }}"
        login: "{{ trap_user }}"
      become: yes
      become_user: "{{ trap_user }}"
      tags: privs